services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: sew_twirly
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/dev
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://sew_twirly:password@db:5432/sew_twirly_development
      RAILS_ENV: development
      SELENIUM_URL: http://chrome:4444/wd/hub
      BINDING: 0.0.0.0
    tty: true
    stdin_open: true

  chrome:
    image: selenium/standalone-chromium:latest
    ports:
      - "4444:4444"

volumes:
  postgres_data:
  bundle_cache:
