version: '3'
services:
  db:
    image: postgres
  web:
    stdin_open: true
    tty: true
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/milliemae
    ports:
      - "3000:3000"
    depends_on:
      - db
