version: '3'
services:
  db:
    build:
      context: .docker/db
    ports:
      - "5432:5432"
  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
    image: milliemae_web
    command: .docker/web/startup
    volumes:
      - .:/app
      - ./bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - 'BUNDLE_PATH=/bundle'
      - 'GEM_HOME=/bundle'
  webpacker:
    tty: true
    stdin_open: true
    image: milliemae_web
    command: .docker/webpacker/startup
    volumes:
      - .:/app
      - ./bundle:/bundle
    depends_on:
      - db
      - web
    environment:
      - 'BUNDLE_PATH=/bundle'
      - 'GEM_HOME=/bundle'
